name: Create Resource Group

on:
  push:
    branches:
      - raju_rgcreation
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose the environment to deploy the Terraform code
        options: 
        - nonprod
        - qa
        - prod

permissions:
  contents: read

jobs:
  Create-Resource-Group:
    name: 'Create Resource Group'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    
    - name: Login to Azure 
      run: |
        az login --service-principal -u "f0a2d8fe-8543-4bfa-b024-48a9f84bef8e" -p "K1K8Q~fP~kdskV1Iwy5qI46qEynSIqgZGwxWqaR7" --tenant "365b7084-5c3e-4b25-8a5e-18fb4e9bd8d5" >/dev/null

    - name: Create Resource Group
      run: |
        az group create \
          --name BackstageTesting \
          --location eastus
