name: 'raju_rgcreationwf'

on:
  push:
    branches:
      - raju_rgcreation
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose the environment to deploy the Terraform code
        options: 
        - nonprod
        - qa
        - prod
      destroy_resources:
        type: boolean
        description: 'Run Terraform Destroy'
        required: false        

permissions:
  contents: read

jobs:
  Terraform_Create:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    
    - name: Login to Azure 
      run: |
        az login --service-principal -u "f0a2d8fe-8543-4bfa-b024-48a9f84bef8e" -p "K1K8Q~fP~kdskV1Iwy5qI46qEynSIqgZGwxWqaR7" --tenant "365b7084-5c3e-4b25-8a5e-18fb4e9bd8d5" >/dev/null

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Change directory to Terraform environment
      run: |
        cd ${{ env.TF_Workspace }}
        echo "TF_Workspace is ${{ env.TF_Workspace }}"
        ls -la   # List files and directories in the current directory
        pwd      # Print the current working directory        
    - name: Terraform Init
      run: |
        cd ${{ env.TF_Workspace }}
        terraform init 
    - name: Terraform Plan
      run: |
        cd ${{ env.TF_Workspace }}
        terraform plan -input=false
    - name: Terraform Apply
      run: |
        cd ${{ env.TF_Workspace }}
        terraform apply -auto-approve -input=false || true
    - name: Terraform Destroy
      if: ${{ github.event.inputs.destroy_resources == 'true' }}
      run: |
        cd ${{ env.TF_Workspace }} && terraform destroy -auto-approve
